# Web Developers Salary Reports (Canada)

## Import Libraries

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Import Dataset

In [18]:
dataset = pd.read_csv("WD_salaries_Canada.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [19]:
print(X)

[['Toronto' 5.1]
 ['Calgary' 1.4]
 ['Calgary' 8.6]
 ['Calgary' 6.7]
 ['Calgary' 2.2]
 ['Montreal' 4.9]
 ['Vancouver' 7.4]
 ['Vancouver' 8.5]
 ['Halifax' 2.3]
 ['Calgary' 4.0]
 ['Montreal' 3.1]
 ['Vancouver' 6.2]
 ['Toronto' 7.3]
 ['Montreal' 5.4]
 ['Halifax' 7.5]
 ['Toronto' 3.6]
 ['Toronto' 8.7]
 ['Toronto' 6.8]
 ['Vancouver' 3.9]
 ['Halifax' 3.0]
 ['Toronto' 4.1]
 ['Montreal' 1.2]
 ['Calgary' 7.3]
 ['Calgary' 3.4]
 ['Toronto' 1.5]
 ['Montreal' 8.6]
 ['Halifax' 4.7]
 ['Vancouver' 1.8]
 ['Vancouver' 5.9]
 ['Calgary' 5.0]
 ['Vancouver' 2.1]
 ['Halifax' 8.2]
 ['Vancouver' 4.3]
 ['Halifax' 5.4]
 ['Halifax' 1.5]
 ['Montreal' 6.6]
 ['Montreal' 2.7]
 ['Halifax' 6.8]
 ['Toronto' 2.9]
 ['Montreal' 7.0]]


In [20]:
print(y)

[ 96000  54000 146000 103000  64000  82000 127000 160000  55000  81000
  72000 114000 134000  91000 110000  75000 161000 110000  83000  63000
  83000  50000 122000  73000  52000 150000  71000  55000 102000  97000
  71000 132000  90000  89000  47000 101000  60000  97000  67000 120000]


# Encoding Categorical Data

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [0])], remainder="passthrough")
X = np.array(ct.fit_transform(X))

In [22]:
print(X)

[[0.0 0.0 0.0 1.0 0.0 5.1]
 [1.0 0.0 0.0 0.0 0.0 1.4]
 [1.0 0.0 0.0 0.0 0.0 8.6]
 [1.0 0.0 0.0 0.0 0.0 6.7]
 [1.0 0.0 0.0 0.0 0.0 2.2]
 [0.0 0.0 1.0 0.0 0.0 4.9]
 [0.0 0.0 0.0 0.0 1.0 7.4]
 [0.0 0.0 0.0 0.0 1.0 8.5]
 [0.0 1.0 0.0 0.0 0.0 2.3]
 [1.0 0.0 0.0 0.0 0.0 4.0]
 [0.0 0.0 1.0 0.0 0.0 3.1]
 [0.0 0.0 0.0 0.0 1.0 6.2]
 [0.0 0.0 0.0 1.0 0.0 7.3]
 [0.0 0.0 1.0 0.0 0.0 5.4]
 [0.0 1.0 0.0 0.0 0.0 7.5]
 [0.0 0.0 0.0 1.0 0.0 3.6]
 [0.0 0.0 0.0 1.0 0.0 8.7]
 [0.0 0.0 0.0 1.0 0.0 6.8]
 [0.0 0.0 0.0 0.0 1.0 3.9]
 [0.0 1.0 0.0 0.0 0.0 3.0]
 [0.0 0.0 0.0 1.0 0.0 4.1]
 [0.0 0.0 1.0 0.0 0.0 1.2]
 [1.0 0.0 0.0 0.0 0.0 7.3]
 [1.0 0.0 0.0 0.0 0.0 3.4]
 [0.0 0.0 0.0 1.0 0.0 1.5]
 [0.0 0.0 1.0 0.0 0.0 8.6]
 [0.0 1.0 0.0 0.0 0.0 4.7]
 [0.0 0.0 0.0 0.0 1.0 1.8]
 [0.0 0.0 0.0 0.0 1.0 5.9]
 [1.0 0.0 0.0 0.0 0.0 5.0]
 [0.0 0.0 0.0 0.0 1.0 2.1]
 [0.0 1.0 0.0 0.0 0.0 8.2]
 [0.0 0.0 0.0 0.0 1.0 4.3]
 [0.0 1.0 0.0 0.0 0.0 5.4]
 [0.0 1.0 0.0 0.0 0.0 1.5]
 [0.0 0.0 1.0 0.0 0.0 6.6]
 [0.0 0.0 1.0 0.0 0.0 2.7]
 

# Splitting the dataset into the Training set and Test set

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)